### ISSUE TITLE
GCWeb forms use a signficiantly smaller font size than its standard font, can't be overridden

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/GCWeb#1634]
#1449 added CSS selectors that effectively decrease the font size of all forms, with no corresponding class that can override them. Code comments indicate that was intended to be a temporary measure. However, it's now 14 months later and the status quo remains.

IMO this is problematic. Form text (e.g. ``chkbxrdio-grp`` legends, labels, etc...) currently looks very small compared to GCWeb v2's "standard" font size. It's somewhat noticeable when navigating across pages on Canada.ca. But it's especially obvious when a page contains a mix of regular content and a form. The regular content ends up looking much bigger than the form's content.

@duboisp @GormFrank Are there any imminent plans to remove the aforementioned selector? If not, could a class potentially be added to allow newer forms to take on GCWeb v2's standard font size?

**Here's an excerpt of the [CSS selector in question](https://github.com/wet-boew/GCWeb/blob/1bcd825894ac592f7655cd5ee2785093be16792c/src/_defaults.scss#L131-L143):**
```scss
/* Exclude temporary the form element from the font update, keep same style as before
 * - Rational: More testing and various adjustment need to be completed before to apply it
 */
:not(#wb-srch) form, .checkbox, .checkbox-inline, .radio, .radio-inline, form .btn:not(.btn-call-to-action) {
	font-size: 16px;
	line-height: 23px;
}
form .btn:not(.btn-call-to-action), .form-control {
	padding: 6px 12px;
}
legend {
	line-height: 1.65em;
}
```
