### ISSUE TITLE
Default table style conflicts with .table-bordered style

### ISSUE THREAD

**Issue by cfarquharson** [wet-boew/GCWeb#329]
A basic table is fine looking like this: http://getbootstrap.com/css/#tables and if there is a need to add borders to it, BS has a class for that called .table-bordered .  Therefore we should REMOVE this custom CSS in theme.css 

```css
th {
    background-color: #CCCCCC;
    border: 1px solid #DDDDDD;
    color: #000000;
    font-weight: 400;
    padding: 8px;
}

table {
    border: 1px solid #DDDDDD;
}
```

That said, BS doesn't apply any CSS directly to the table elements and requires you to apply a class 'table' to the table itself.  This is to make sure that other items, like date pickers etc don't inherit the properties.  

So if you are going to apply styles directly to the elements, it should be noticed that BS has a lot more CSS that we are missing.  Here's a quick example of the CSS we don't have unless the .table class is applied!!

```css
.table > caption + thead > tr:first-child > th, .table > colgroup + thead > tr:first-child > th, .table > thead:first-child > tr:first-child > th, .table > caption + thead > tr:first-child > td, .table > colgroup + thead > tr:first-child > td, .table > thead:first-child > tr:first-child > td {
    border-top: 0 none;
}
.table > thead > tr > th {
    border-bottom: 2px solid #DDDDDD;
    vertical-align: bottom;
}
.table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {
    border-top: 1px solid #DDDDDD;
    line-height: 1.42857;
    padding: 8px;
    vertical-align: top;
}
```
