### ISSUE TITLE
"Share this page" overlay heading bottom border issue

### ISSUE THREAD

**Issue by biljanap** [wet-boew/GCWeb#631]
There is red bottom border applied to Share this page overlay heading. It probably comes from:

``` css
.home h2, .home .departments h3 {
  border-bottom: 1px solid #AF3C43;
}
```

See screenshot at https://github.com/wet-boew/wet-boew/issues/4976
