### ISSUE TITLE
CSS: IE8: backdrop.png

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/GCWeb#790]
Do we still need this line of code for IE8?

https://github.com/wet-boew/GCWeb/blob/master/src/tabs/_screen.scss#L32

``` scss
.lt-ie9 {
   .prm-flpr {
      .carousel-s2 {
         figcaption {
            background: url("../assets/backdrop.png");
         }
      }
   }
}
```

I will look into it later. But if someone else has the time, go right ahead.
